w3c/epubcheck

.travis.yml, src/main/java/com/adobe/epubcheck/util/ValidatorMap.java
- loosen the generics restriction of method signatures
- add a jdk build matrix to the Travis config to make it compile on Java 6, 7 & 8
=> Fix the compilation of ValidatorMap on Java 6

src/main/java/com/adobe/epubcheck/bitmap/BitmapChecker.java, src/main/java/com/adobe/epubcheck/messages/MessageDictionary.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/java/com/adobe/epubcheck/test/message_coverage.java
When running Java 6, any `LinkageError` thrown at runtime due to
incompatibility of the TwelveMonkeys ImageIO plugin is caught and
an info message is displayed.
Note: building on Java 6 remains unsupported (some tests fail due to
lesser image checking).
=> Re-enable runtime support for Java 6

src/main/resources/com/adobe/epubcheck/schema/30/media-overlay-30.nvdl, src/main/resources/com/adobe/epubcheck/schema/30/ocf-container-30.nvdl, src/main/resources/com/adobe/epubcheck/schema/30/ocf-metadata-30.nvdl, src/main/resources/com/adobe/epubcheck/schema/30/package-30.nvdl
See issue #601 for details.
Note: NVDL schemas are currently not used by EpubCheck, but this fix
at least make them usable by 3d party tools.
Fixes #601.
=> Fix ns validation issue in NVDLs

src/main/resources/com/adobe/epubcheck/schema/30/epub-xhtml-30.sch, src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java, src/test/resources/30/single/xhtml/valid/http-equiv-2.xhtml
An HTML meta element with `http-equiv` in character encoding declaration
state must be parsed in a case insensitive manner.
This commit fixes a Schematron typo (the `'i'` parameter of the `matches`
function was unquoted, hence evaluated as an empty sequence instead
of a string, which was consequently ignored) to propertly enable a
case-insenstive comparison.
Fixes #603
=> Fix case insensitive check of XHTML encoding declaration

src/main/resources/com/adobe/epubcheck/messages/MessageBundle_nl.properties, src/main/resources/com/adobe/epubcheck/util/messages_nl.properties, src/main/resources/org/idpf/epubcheck/util/css/messages_nl.properties
Thanks to Merijn de Haen who contributed this translation on Transifex!
Pulled from Transifex by @tofi86 with no changes to the properties files.
=> Added dutch translation for epubcheck 4.0

src/main/java/com/adobe/epubcheck/vocab/AggregateVocab.java, src/main/java/com/adobe/epubcheck/vocab/EnumVocab.java, src/main/java/com/adobe/epubcheck/vocab/UncheckedVocab.java, src/main/java/com/adobe/epubcheck/vocab/Vocab.java, src/main/java/com/adobe/epubcheck/vocab/VocabUtil.java, src/test/java/com/adobe/epubcheck/opf/OPFCheckerTest.java, src/test/resources/30/single/opf/invalid/prefixes-redeclare.opf
- added a new method to `Vocab` to get the base URI of a vocabulary
- In the prefix parsing utility of `VocabUtil`, check the URI associated
with re-declared reserved prefix: an error is reported only if this
URI is **not** the URI of the known vocabulary associated to the
reserved prefix. In other words, explicit declaration of reserved
prefixes is now allowed; trying to override a reserved prefix still
raises an error.
Fixes #585
=> Ignore explicit declarations of reserved prefixes

src/main/java/com/adobe/epubcheck/ctc/EpubExtLinksCheck.java, src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java, src/test/java/com/adobe/epubcheck/api/Epub20CheckExpandedTest.java, src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java, src/test/resources/20/expanded/invalid/missing-resource/EPUB/lorem.css, src/test/resources/20/expanded/invalid/missing-resource/EPUB/lorem.ncx, src/test/resources/20/expanded/invalid/missing-resource/EPUB/lorem.opf, src/test/resources/20/expanded/invalid/missing-resource/EPUB/lorem.xhtml, src/test/resources/20/expanded/invalid/missing-resource/META-INF/container.xml, src/test/resources/20/expanded/invalid/missing-resource/mimetype, src/test/resources/30/expanded/invalid/resource-missing-refinxhtml/EPUB/lorem.css, src/test/resources/30/expanded/invalid/resource-missing-refinxhtml/EPUB/lorem.opf, src/test/resources/30/expanded/invalid/resource-missing-refinxhtml/EPUB/lorem.xhtml, src/test/resources/30/expanded/invalid/resource-missing-refinxhtml/META-INF/container.xml, src/test/resources/30/expanded/invalid/resource-missing-refinxhtml/mimetype, src/test/resources/com/adobe/epubcheck/test/xhtml/hyperlinks_expected_results.json
An image file was not declared in the OPF and not present in the
package but referenced in an XHTML document was reported twice,
as RSC-001 and RSC-007.
The duplicated report (from the extra link checker in the `ctc`
package) has been removed, in favor of the existing RSC-007.
Fixes #588
=> Remove duplicate reporting of missing images

src/main/java/com/adobe/epubcheck/ctc/XmlDocParser.java, src/main/java/com/adobe/epubcheck/ctc/xml/XMLContentDocParser.java, src/test/java/com/adobe/epubcheck/api/Epub20CheckTest.java, src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java, src/test/resources/30/expanded/invalid/encryption-unknown/EPUB/lorem.css, src/test/resources/30/expanded/invalid/encryption-unknown/EPUB/lorem.opf, src/test/resources/30/expanded/invalid/encryption-unknown/EPUB/lorem.xhtml, src/test/resources/30/expanded/invalid/encryption-unknown/META-INF/container.xml, src/test/resources/30/expanded/invalid/encryption-unknown/META-INF/encryption.xml, src/test/resources/30/expanded/invalid/encryption-unknown/mimetype
The XML parsers triggered in the `ctc` package were sometimes
reporting PKG-008 (on IOException) or RSC-005 (on SAXException).
These were duplicates, such parsing errors are caught earlier (if
they're not, it's a bug).
Also added a simple test case for an encrypted EPUB with unknown
encryption algorithm.
Fixes #593.
=> Avoid duplicate PKG-008 or RSC-005 XML parsing errors

src/main/resources/com/adobe/epubcheck/schema/30/epub-xhtml-30.sch, src/test/resources/30/single/xhtml/valid/tables-001.xhtml
The HTML specification says:
> A string containing a set of space-separated tokens may have leading
or trailing space characters.
This commit normalizes whitespace of attributes for which every token
is checked (like "unordered set of unique space-separated tokens"
aka IDREFS).
Fixes #622.
=> Fix tokenization of sets of space-separated tokens in Schematron

src/main/java/com/adobe/epubcheck/ctc/EntitySearch.java, src/main/java/com/adobe/epubcheck/ctc/EpubHTML5StructureCheck.java, src/main/java/com/adobe/epubcheck/ctc/EpubRenditionCheck.java, src/main/java/com/adobe/epubcheck/util/Archive.java, src/main/java/org/idpf/epubcheck/util/css/CssGrammar.java, src/test/java/com/adobe/epubcheck/stress/StressTest.java, src/test/java/com/adobe/epubcheck/test/debug.java, src/test/java/org/idpf/epubcheck/util/css/CssInputStreamTest.java
The codebase would need a bigger cleanup anyways, so this is just a minor code cleanup after an initial lint4j check.
Came to my mind when looking for other (#689) unclosed InputStreams...
=> Minor code cleanup after lint4j check

src/main/java/com/adobe/epubcheck/util/Archive.java
When using EpubCheck in projects I often use the `Archive` class to zip up an extracted epub folder.
However, until now, there has been no possibility to specify the output path for the `Archive.createArchive()` method.
This sometimes results in overridden epub files when you extract an existing epub file in the same folder and then check the extracted folder with EpubCheck. Not good.
With this PR I add a new overloaded method `createArchive(File absoluteEpubFilePath)` to change the output destination for the ZIP file.
This affects no existing functionality so I'm sure, we can merge this for the next release, right @rdeltour ?
=> add Archive.createArchive(File) method

src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java
that tests that the case transformations are indeed locale-independent.
Better testing of fix for issue #711.
=> Improves Epub30CheckExpandedTest.testPageList() by actually setting an appropriate default locale for the duration of the test 

src/main/java/com/adobe/epubcheck/messages/MessageDictionary.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/ops/OPSHandler.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java, src/test/resources/30/single/xhtml/invalid/url-checks_issue-708.xhtml
Add new Warning(RSC-023) when host of HTTP-URL is null (fixes #708).
Catches URL typos like `https:/www` or `https:www`
----
Plus: also report HTTPS URLs in the list of references (c3c9204)
=> Add better url checks

src/main/resources/com/adobe/epubcheck/schema/30/media-overlay-30.sch, src/test/java/com/adobe/epubcheck/overlay/OverlayCheckerTest.java, src/test/resources/30/single/overlays/invalid/overlay-008.smil
This is an attempt to fix #568.
However, this is only a very very basic check which just compares the two attributes and doesn't check for same timestamps in different syntaxes.
Please see issue #568 for ongoing discussion on this topic...
=> [fix #568] Added SMIL schematron check to report when @clipBegin==@clipEnd

src/main/resources/com/adobe/epubcheck/schema/20/rng/opf20.rng, src/test/java/com/adobe/epubcheck/opf/OPFCheckerTest.java, src/test/resources/20/single/opf/invalid/issue663_empty-guide.opf
fixes #663 
This change is in sync with the official OPF schema at http://www.idpf.org/epub/20/spec/OPF_2.0_latest.htm#AppendixA
A test has been added.
=> [fix #663] Update the OPF20 RNG schema partially to validate empty guide elements

src/main/java/com/adobe/epubcheck/tool/EpubChecker.java
Set `-Djava.awt.headless=true` in `EpubChecker` class to fix #665 (_GUI focus stolen due to epubcheck launching window-less “Checker” empty GUI app_)
Needs to be set as early as possible in a static way.
=> [fix #665] Set -Djava.awt.headless=true in EpubChecker class

src/main/java/com/adobe/epubcheck/css/CSSHandler.java, src/main/java/com/adobe/epubcheck/util/XmlReportAbstract.java, src/main/java/com/adobe/epubcheck/util/XmlReportImpl.java, src/test/java/com/adobe/epubcheck/test/css_Test.java, src/test/resources/com/adobe/epubcheck/test/css/font-family-no-src/META-INF/container.xml, src/test/resources/com/adobe/epubcheck/test/css/font-family-no-src/OPS/content.opf, src/test/resources/com/adobe/epubcheck/test/css/font-family-no-src/OPS/external_css.xhtml, src/test/resources/com/adobe/epubcheck/test/css/font-family-no-src/OPS/inline_css.xhtml, src/test/resources/com/adobe/epubcheck/test/css/font-family-no-src/OPS/style_tag_css.xhtml, src/test/resources/com/adobe/epubcheck/test/css/font-family-no-src/OPS/styles/style.css, src/test/resources/com/adobe/epubcheck/test/css/font-family-no-src/OPS/toc.ncx, src/test/resources/com/adobe/epubcheck/test/css/font-family-no-src/OPS/toc.xhtml, src/test/resources/com/adobe/epubcheck/test/css/font-family-no-src/mimetype, src/test/resources/com/adobe/epubcheck/test/css/font-family-no-src_expected_results.xml, src/test/resources/com/adobe/epubcheck/test/css/font_encryption_idpf_expected_results.xml, src/test/resources/com/adobe/epubcheck/test/encryption/epub30_font_obfuscation.epub_expected_results.xml
Avoid storing 'null' value in feature
Handle no src uri in fonts, fixes #773, 
Add a unit test 'font-family-no-src' to test for the case refer in #773 
Correct embedded font boolean in xml output
=> [Fix 773] No empty references in XML output

src/main/resources/com/adobe/epubcheck/schema/30/mod/datatypes.rnc, src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/html5-attrib-30.rnc, src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/html5-embed-30.rnc, src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java, src/test/resources/30/single/xhtml/valid/issue777-empty-lang.xhtml
This pull request is to address #777.
=> [fix #777] Allow xml:lnag="" by replacing datatype.languagecode by datatype.languagecode | string "".

src/main/resources/com/adobe/epubcheck/schema/30/epub-svg-30.rnc, src/main/resources/com/adobe/epubcheck/schema/30/mod/datatypes.rnc, src/main/resources/com/adobe/epubcheck/schema/30/mod/epub-svg11-30.rnc, src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/html5-attrib-30.rnc, src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/html5-embed-30.rnc, src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java, src/test/resources/30/single/svg/valid/issue769.xhtml
Schema changes required for addressing #769.  Not unit tests (sorry!).
=> Fix 769 allowing aria role attributes in svg

src/main/java/com/adobe/epubcheck/api/MasterReport.java, src/main/java/com/adobe/epubcheck/api/Report.java, src/main/java/com/adobe/epubcheck/tool/EpubChecker.java, src/main/resources/com/adobe/epubcheck/util/messages.properties, src/test/resources/com/adobe/epubcheck/test/command_line/severity_error_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_fatal_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideBadId_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideBadMessage_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideBadSeverity_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideMissingFile_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideOk_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_usage_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_warning_expected_results.txt
fixes #655
To be able to implement this I had to change the `Report` interface and add two new methods `getInfoCount()` and `getUsageCount()`.
However, this change may break existing Java implementations using the plain `Report` interface instead inheriting from `MasterReport`.
So this definately needs to be in a Minor release rather than a Bugfix release.
=> [fix #655] display error/warning count in EpubCheck result

src/main/resources/com/adobe/epubcheck/schema/20/rng/opf20.rng
When working on #663 and #724 I came across the fact, that the OPF RNG schema in EpubCheck is not up to date.
Schema from http://www.idpf.org/epub/20/spec/OPF_2.0_latest.htm#AppendixA differs in several places from the EpubCheck schema in `src/main/resources/com/adobe/epubcheck/schema/20/rng/opf20.rng`.
I'm not familiar with the process of updating official schemas in the EpubCheck project, so how are the analogues DTDs handled? Where do they come from?
Also: it seems for EpubCheck the RNG `<start>` element must not be present in order to be able to run the checker... right?
Note: the initial commit on this PR breaks the build. The OPF 2.0 schema update obviously has side-effects on the tests which needs to be handled... How?
IMHO, this may also be a reason to make the next release …
=> Update OPF 2.0 RNG schema partially to latest version (changing datatype text to anyURI for href attributes)

src/main/java/com/adobe/epubcheck/ocf/OCFChecker.java, src/test/java/com/adobe/epubcheck/api/Epub20CheckTest.java, src/test/java/com/adobe/epubcheck/test/message_coverage.java
```
$ java -Duser.language=en -jar target/epubcheck.jar -u --profile preview src/test/resources/20/epub/valid/lorem.epub 
Validating using EPUB version 2.0.1 rules.
USAGE(PKG-023): src/test/resources/20/epub/valid/lorem.epub/EPUB/lorem.opf(-1,-1): Validating the EPUB against version 2.0, default validation profile will be used.
ERROR(RSC-005): src/test/resources/20/epub/valid/lorem.epub/EPUB/lorem.opf(3,59): Error while parsing file: An EPUB Preview publication must have a 'preview' dc:type.
WARNING(RSC-017): src/test/resources/20/epub/valid/lorem.epub/EPUB/lorem.opf(3,59): Warning while parsing file: An EPUB Preview publication should link back to its source Publication using a dc:source element.
USAGE(HTM-010): src/test/resources/20/epub/valid/lorem.epub/EPUB/lorem.ncx(5,19): Namespace …
```
=> use default validation profile against EPUB 2.0 file

src/main/java/com/adobe/epubcheck/api/EpubCheck.java, src/main/java/com/adobe/epubcheck/util/CheckUtil.java, src/test/java/com/adobe/epubcheck/ocf/OCFCheckerTest.java
* To check that mimetype file in EPUB is not comressed, add a check in `checkEpubHeader()`
* to avoid checking twice, ignore some checks in `checkTrailingSpaces()`
For EPUB files in https://github.com/IDPF/epubcheck/issues/303#issuecomment-260916592 , epubcheck with this patch finds 1 error in epub30-spec_compressed.epub , but no errors in epub30-spec_uncompressed.epub.
=> [fix #303] Check MimeType uncompressed

src/main/java/com/adobe/epubcheck/messages/MessageDictionary.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/opf/OPFChecker.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/java/com/adobe/epubcheck/api/Epub20CheckTest.java
fixes #666 
Catch errors when initializing of NCXChacker, NavChecker and other Checker classes' object and report CHK_008, new MessageId instance.
This PR is not complete solution of `Preconditions.checkXXX` methods issue said https://github.com/IDPF/epubcheck/issues/666#issuecomment-175738402, but may be a reasonable workaround.
=> [fix #666] handle IllegalStateException in checkItemContent

.travis.yml
to use deprecated trusty image after [failures](https://travis-ci.org/IDPF/epubcheck/jobs/276550358)
https://blog.travis-ci.com/2017-08-29-trusty-image-updates
=> Updating Travis config to use openjdk7 instead of oraclejdk7 which isn't supported by Travis anymore

README.md, pom.xml
* Require minimum maven version in `pom.xml` as described in `README.md`
* Upgraded maven build plugins as suggested by `mvn versions:display-plugin-updates`
=> [Build] Require Maven 3.0 and update build dependencies

pom.xml, src/main/java/com/adobe/epubcheck/vocab/PrefixDeclarationParser.java, src/main/java/com/adobe/epubcheck/xml/XMLValidator.java, src/main/java/org/idpf/epubcheck/util/saxon/Int64ValueSequence.java, src/main/java/org/idpf/epubcheck/util/saxon/SystemIdFunction.java
Update Saxon with respect of the latest Saxon API changes.
=> [fix #647] Update Saxon dependency from 9.5.1-5 to 9.6.0-10

pom.xml
Update Saxon dependency to latest 9.7 release.
The latest release in 9.7 branch is 9.7.0-21.
The source code for Saxon-HE is available on SourceForge:
https://sourceforge.net/projects/saxon/files/Saxon-HE/9.7/
resolves #674
=> [fix #674] update Saxon dependency to latest 9.7 release

pom.xml, src/main/java/com/adobe/epubcheck/xml/XMLValidator.java
As @raducoravu mentioned in https://github.com/IDPF/epubcheck/issues/674#issuecomment-364250337, Saxon 9.8.0-7 HE supports XSLT 1.0 again. So I've made some minor changes to `XMLValidator.java` related to some API differences between Saxon 9.7 and 9.8. All tests have been passed.
=> update to saxon 9.8.0-7

pom.xml, src/main/java/org/idpf/epubcheck/util/css/CssEscape.java, src/main/java/org/idpf/epubcheck/util/css/CssExceptions.java, src/main/java/org/idpf/epubcheck/util/css/CssGrammar.java, src/main/java/org/idpf/epubcheck/util/css/CssLocation.java, src/main/java/org/idpf/epubcheck/util/css/CssReader.java, src/main/java/org/idpf/epubcheck/util/css/CssSource.java, src/main/java/org/idpf/epubcheck/util/css/CssToken.java
This is a first attempt to updating Google Guava dependency to v24.0 as suggested by @rdeltour in #832.
However, there seem to be compile issues with Maven, despite Eclipse doesn't report any errors.
=> [fix #832] update Google Guava dependency to v24.0

.travis.yml, pom.xml
- remove Oracle JDK 10 from the build matrix
- add Oracle JDK 11 to the build matrix
- updated `commons-compress` to v1.18 (the previous version had a security vulnerability)
=> Update the Travis JDK build matrix + dependency update

pom.xml, src/main/java/com/adobe/epubcheck/xml/XMLValidator.java, src/test/java/com/adobe/epubcheck/cli/CheckerIT.java
The Schematron XSLT built in Jing as an `/..` XPath expression which
always evaluates to the empty sequence.
Saxon 9.8 consequently raises a SXWN9000 warning, when the validators
are created (statically, during EPUBCheck's intializations).
This PR initalizes Jing's transformer factory with a static error listener
that ignores this warning.
This is tested as an integration test (since the warning is produced
on the standard error stream at initialization time), run via the
Maven failsafe plugin.
Fixes #859
=> Fix issue #859: Saxon warning from Jing's Schematron XSLT

src/main/java/com/adobe/epubcheck/tool/EpubChecker.java, src/main/resources/com/adobe/epubcheck/util/messages.properties
Congrats to release 4.1.0 🎉 
By the way, to translate error messages, the words "incorrect" and "missing" in
com/adobe/epubcheck/tool/EpubChecker.java should be in messages.properties.
=> fix: messages of missing/incorrect locale cannot be translated

src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java, src/test/java/com/adobe/epubcheck/cli/CLITest.java, src/test/java/com/adobe/epubcheck/test/MessageDictionary_LocalizationTest.java, src/test/java/com/adobe/epubcheck/test/UtilMessage_LocalizationTest.java, src/test/java/com/adobe/epubcheck/test/common.java
Some tests were setting the default Locale, but were not setting it back to the original value. This side effect caused later localization tests to fail.
This PR fixes that by making sure the default locale is reset, in a `finally` block, whenever it is explicitly set in tests.
Fixes #916
=> Make sure tests reset the default locale

src/main/java/com/adobe/epubcheck/tool/EpubChecker.java
Refactored "run" and "processEpubFile" file methods to actually run the same code to ensure consistent behavior.
Also removed several duplicate or unused methods.
Reworked "processArguments" method to use regular expressions and a switch statement.
=> Refactored "run" and "processEpubFile" file methods

pom.xml
- The version of Saxon needs to be restricted to a more specific range because Saxon doesn't do semantic versioning.
- Update to more recent version of maven-bundle-plugin to solve a problem when using two versions of jing (20120724.0.0 + a newer one) in the same OSGi application.
=> Some OSGi related changes

src/main/resources/com/adobe/epubcheck/schema/20/sch/opf.sch, src/main/resources/com/adobe/epubcheck/schema/30/epub-nav-30.sch, src/main/resources/com/adobe/epubcheck/schema/30/package-30.sch, src/test/java/com/adobe/epubcheck/nav/NavCheckerTest.java, src/test/resources/30/single/nav/valid/nav-landmarks-noduplicates.xhtml
The XPath in Schematron was using `@html:href` instead of `@href`,
which faked the href equality test.
This change also covers the case of multiple `epub:type` values.
Fixes #926
=> fix: wrong report of duplicate landmarks in Nav Doc

src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java, src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java, src/test/resources/30/expanded/valid/svg-switch/META-INF/container.xml, src/test/resources/30/expanded/valid/svg-switch/OPS/content_001.xhtml, src/test/resources/30/expanded/valid/svg-switch/OPS/nav.xhtml, src/test/resources/30/expanded/valid/svg-switch/OPS/package.opf, src/test/resources/30/expanded/valid/svg-switch/mimetype
The `switch` property of Package Documents `item` elements indicates
that the described Publication Resource contains one or more instances
of the `epub:switch` element. It should not be declared when the EPUB
contains SVG using the `svg:switch` element.
Fixes #857
=> fix: `switch` item property doesn't apply to `svg:switch`

src/main/java/com/adobe/epubcheck/opf/OPFHandler30.java, src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java, src/main/java/com/adobe/epubcheck/vocab/AccessibilityVocab.java, src/main/java/com/adobe/epubcheck/vocab/ComicsVocab.java, src/main/java/com/adobe/epubcheck/vocab/DCMESVocab.java, src/main/java/com/adobe/epubcheck/vocab/DataNavVocab.java, src/main/java/com/adobe/epubcheck/vocab/DictVocab.java, src/main/java/com/adobe/epubcheck/vocab/EnumVocab.java, src/main/java/com/adobe/epubcheck/vocab/IndexVocab.java, src/main/java/com/adobe/epubcheck/vocab/StagingEdupubVocab.java, src/main/java/com/adobe/epubcheck/vocab/StructureVocab.java, src/test/java/com/adobe/epubcheck/opf/OPFCheckerTest.java, src/test/java/com/adobe/epubcheck/vocab/VocabTest.java, src/test/resources/30/single/opf/invalid/vocab-a11y-unknownproperty.opf, src/test/resources/30/single/opf/valid/vocab-a11y-declared.opf, src/test/resources/30/single/opf/valid/vocab-a11y-undeclared.opf
- recognize `a11y` as a reserved prefix
- define meta and link rel voabularies for Accessibility properties
- add tests
Fixes #810
- add a new EnumVocab constructors with a [`CaseFormat`](https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/base/CaseFormat.html) option to be  able to define the rules from converting from the Enum constant to  the property name.  When not specified, the default case format is `LOWER_HYPHEN`.
- replace the `ENUM_TO_NAME` static function by a `Converter` class member (initialized based on the given case format)
- add public methods `getName(P)` and `getNames(Collection<P>)` to get  the string value of property names based on their Enum constant.
- add tests for a vocab specifying the `LOWER_CAMEL` case format
=> Better support for the accessibility vocab

.travis.yml
The builds are now run on `xenial`, where openjdk 10 and 11 are pre-installed.
See also this [Travis CI community discussion](https://travis-ci.community/t/install-of-openjdk11-is-failing/1914).
=> Re-enable openjdk11 on Travis CI

src/main/java/com/adobe/epubcheck/xml/HTMLUtils.java, src/main/java/com/adobe/epubcheck/xml/XMLParser.java, src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java, src/test/resources/30/single/xhtml/valid/attrs-case-insensitive.xhtml, src/test/resources/30/single/xhtml/valid/attrs-custom-ns.xhtml, src/test/resources/30/single/xhtml/valid/custom-elements.xhtml, src/test/resources/30/single/xhtml/valid/custom-ns-attrs.xhtml
- add an `HTMUtils` facility to get whether an HTML attribute has a
case-insensitive value (boolean and enumerated attributes)
- pre-process case-insensitive HTML attributes to lower-case their value
- refactor the pre-processing attribute logic for more clarity
- add a test
Fix #941
- add an `isCustomElement` method in `HTMLUtils`.
- pre-process custom elements in `XMLParser` to put them in the
proprietary namespace used by the Nu Html Checker schemas to treat
them distinctively.
- add a simple test case.
Fix #932
=> normalize HTML case-insensitive attributes + basic support for custom elements

src/main/java/com/adobe/epubcheck/ctc/css/EpubCSSCheckCSSHandler.java, src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/main/resources/com/adobe/epubcheck/messages/MessageBundle_de.properties, src/main/resources/com/adobe/epubcheck/messages/MessageBundle_es.properties, src/main/resources/com/adobe/epubcheck/messages/MessageBundle_fr.properties, src/main/resources/com/adobe/epubcheck/messages/MessageBundle_it.properties, src/main/resources/com/adobe/epubcheck/messages/MessageBundle_ja.properties, src/main/resources/com/adobe/epubcheck/messages/MessageBundle_ko_KR.properties, src/main/resources/com/adobe/epubcheck/messages/MessageBundle_nl.properties, src/main/resources/com/adobe/epubcheck/messages/MessageBundle_pt_BR.properties, src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java, src/test/resources/com/adobe/epubcheck/test/command_line/failonwarnings/OPS/style_tag_css.xhtml, src/test/resources/com/adobe/epubcheck/test/command_line/failonwarnings_expected_results.json, src/test/resources/com/adobe/epubcheck/test/command_line/listSeverities_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity/OPS/style_tag_css.xhtml, src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideBadId_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideBadMessage_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideBadSeverity_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideMissingFile_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideOk_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_usage_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/command_line/severity_warning_expected_results.txt, src/test/resources/com/adobe/epubcheck/test/css/discouraged_expected_results.json, src/test/resources/com/adobe/epubcheck/test/css/discouraged_expected_results.xml
This PR addresses #899 in the following ways:
- lowers CSS-006 and CSS-017 from WARNING to USAGE
- deletes CSS-027 as it becomes redundant with -017
Making these changes resulted in no warnings in the command line tests, though, so to add one back I deleted the title from one of the XHTML content documents. We don't have any CSS warnings in the specification, and my limited imagination couldn't come up with any other warnings for HTML.
=> Change css position warnings to usage messages

src/main/java/com/adobe/epubcheck/opf/OPFChecker30.java, src/test/resources/30/single/opf/valid/cmt.opf
This PR fixes #872 by allowing resources declared as font/* to be recognized as core media types, since fonts don't require fallbacks.
=> Allow font/* as blessed media types

src/main/resources/com/adobe/epubcheck/schema/30/ocf-encryption-30.rnc, src/test/java/com/adobe/epubcheck/ocf/OCFCheckerTest.java, src/test/resources/30/expanded/invalid/ocf-compression/EPUB/content_001.xhtml, src/test/resources/30/expanded/invalid/ocf-compression/EPUB/nav.xhtml, src/test/resources/30/expanded/invalid/ocf-compression/EPUB/package.opf, src/test/resources/30/expanded/invalid/ocf-compression/META-INF/container.xml, src/test/resources/30/expanded/invalid/ocf-compression/META-INF/encryption.xml, src/test/resources/30/expanded/invalid/ocf-compression/mimetype, src/test/resources/30/expanded/valid/ocf-compression/EPUB/content_001.xhtml, src/test/resources/30/expanded/valid/ocf-compression/EPUB/nav.xhtml, src/test/resources/30/expanded/valid/ocf-compression/EPUB/package.opf, src/test/resources/30/expanded/valid/ocf-compression/META-INF/container.xml, src/test/resources/30/expanded/valid/ocf-compression/META-INF/encryption.xml, src/test/resources/30/expanded/valid/ocf-compression/mimetype
This PR adds the Compression element that was introduced in the 3.1 schema. Fixes #904
=> Add the Compression element

src/main/resources/com/adobe/epubcheck/schema/30/mod/epub-svg11.rnc, src/main/resources/com/adobe/epubcheck/schema/30/mod/epub-xhtml-svg11.rnc, src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java, src/test/resources/30/single/svg/valid/aria-attributes.svg
Add `aria.global` attributes to `SVG.Core.attrib`, in both SVG and XHTML
integration schemas.
Fix #846
Thanks @mattgarrish for the schema spelunking!
=> Support global ARIA attributes in SVG

src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/structural.rnc
This PR fixes #997 by allowing doc-glossary on section element.
Probably should include some tests, but we don't test any of the roles so figuring we can deal with that at a later time.
=> Add doc-glossary to section

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java, src/test/resources/30/expanded/invalid/script-property-undeclared/META-INF/container.xml, src/test/resources/30/expanded/invalid/script-property-undeclared/OPS/content_001.xhtml, src/test/resources/30/expanded/invalid/script-property-undeclared/OPS/nav.xhtml, src/test/resources/30/expanded/invalid/script-property-undeclared/OPS/package.opf, src/test/resources/30/expanded/invalid/script-property-undeclared/mimetype, src/test/resources/30/expanded/valid/script-data-block/META-INF/container.xml, src/test/resources/30/expanded/valid/script-data-block/OPS/content_001.xhtml, src/test/resources/30/expanded/valid/script-data-block/OPS/nav.xhtml, src/test/resources/30/expanded/valid/script-data-block/OPS/package.opf, src/test/resources/30/expanded/valid/script-data-block/mimetype, src/test/resources/com/adobe/epubcheck/test/scripts/properties_expected_results.json
Content Documents with script data blocks (`script` elements with inline
data that isn't Javascript) should not need to be declared as `scripted`
in the Package Document.
`OPF_014` reports missing item properties, and already only reports a
missing `scipted` property when Javascript-typed `script` is found.
But `SCP_005` was also raised as `ERROR`, duplicating `OPF_014`, and
incorrectly _not_ depending on the script type.
This PR fixes that by suppressing message `SCP_005`.
=> fix: script data blocks don't need to be declared

src/main/resources/com/adobe/epubcheck/schema/30/epub-nav-30.sch, src/test/java/com/adobe/epubcheck/nav/NavCheckerTest.java
They were previously reported as WARNING.
Close #298
=> fix: report duplicate landmarks nav entries as ERROR

src/main/java/org/idpf/epubcheck/util/css/CssScanner.java, src/test/java/org/idpf/epubcheck/util/css/CssParserTest.java, src/test/java/org/idpf/epubcheck/util/css/CssScannerTest.java, src/test/resources/css/custom-properties.css
This change only fixes the `CssScanner` to parse CSS custom properties
as IDENT tokens.
Additional work may be needed to actually make the built-in CSS Grammar
aware of custom properties, but at this time this is not needed to
prevent EPUBCheck from reporting custom properties as errors.
Fix #790
=> fix: parse CSS custom properties

src/main/resources/com/adobe/epubcheck/schema/30/epub-nav-30.rnc, src/main/resources/com/adobe/epubcheck/schema/30/mod/epub-type-attr.rnc, src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java, src/test/resources/30/single/xhtml/valid/epubtype-in-head.xhtml
=> fix: allow `epub:type` on all HTML elements

src/main/java/com/adobe/epubcheck/ctc/EpubSVGCheck.java, src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/opf/ValidationContext.java, src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java, src/test/resources/com/adobe/epubcheck/test/opf/viewport_expected_results.json
Message changes:
- `HTM-048` now checks that outermost `svg` elements in Fixed-Layout
Documents MUST have a `viewBox` attribute.
- remove `HTM-054` (`viewBox` recommended)
- remove `HTM-055` (height+width in percent when `viewBox` is abstent)
- remove old suppressed message `HTM-043`
Internal changes:
- move the SVG FXL logic out of the `ctc` package
- add an `Optional<OPFItem>` field to the validator context (retrieved
from the `XRefChecker` in the builder, or absent).
This PR (partially) reverts commit 17f5eeedbbb845703a9821ce38a059a4fb392ffa
See also w3c/publ-epub-revision#1236
=> fix: revert FXL SVG rules to EPUB 3.0.1’s logic

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/opf/OPFChecker30.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/java/com/adobe/epubcheck/opf/OPFCheckerTest.java, src/test/resources/30/single/opf/valid/cmt-preferred.opf, src/test/resources/com/adobe/epubcheck/test/css/font-face_expected_results.json, src/test/resources/com/adobe/epubcheck/test/css/font-face_expected_results.xmp, src/test/resources/com/adobe/epubcheck/test/css/font_encryption_idpf_expected_results.json, src/test/resources/com/adobe/epubcheck/test/css/font_encryption_idpf_expected_results.xml, src/test/resources/com/adobe/epubcheck/test/css/font_encryption_idpf_expected_results.xmp, src/test/resources/com/adobe/epubcheck/test/scripts/XMLHttpRequest_expected_results.json, src/test/resources/com/adobe/epubcheck/test/scripts/eval_expected_results.json, src/test/resources/com/adobe/epubcheck/test/scripts/properties_expected_results.json, src/test/resources/com/adobe/epubcheck/test/scripts/storage_expected_results.json, src/test/resources/com/adobe/epubcheck/test/scripts/unused_expected_results.json, src/test/resources/com/adobe/epubcheck/test/xhtml/media_overlays_expected_results.json
Report a new `USAGE` message, `OPF-090`, when a Package Doc item is
declared with a Core Media Type which has an alternative preferred media
type.
Fix #873
=> feat: report use of non-preferred Core Media Types

src/main/assembly/README-dist.txt
I just added new translations from Transifex:
* **Chinese (Taiwan)** 46195adc2a88ef45ef6341bb424804980f3857db
* **Danish** 28ef69bea729073186890117611c616672e64fc7
I just updated existing translations from Transifex:
* **Italian** 864282a6245007a6b08d3c1d57c2da6db2da5fa0 and d954ae7b9b90d373378e3c6622ba40bb7d42f5d0
However, Transifex does not show who translated the messages, who contributed.
Dear contributors, we highly value your efforts in translation EPUBCheck and would like to add your name to the list of contributors in the README file. 🙏 
Please leave me a comment  here if you contributed to one of the languages above and I will add you to the list. Thanks.
=> Add l10n contributors to the dist README

src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/phrase.rnc, src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java, src/test/resources/30/single/xhtml/valid/aria-role-a-nohref.xhtml
Any role is allowed according to ARIA in HTML:
https://www.w3.org/TR/html-aria/#anohref
Ported from validator/validator#774
Fix #1022
=> fix: allow any role on `a` elem with no `href`

src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/block.rnc, src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/phrase.rnc, src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java, src/test/resources/30/single/xhtml/valid/aria-role-doc-endnote.xhtml
=> fix: allow `doc-endnote` on `li` children of `ol`

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/opf/XRefChecker.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java
As agreed on the 2019-07-11 EPUB CG call:
https://www.w3.org/2019/07/11-epub3cg-minutes.html
Changes the behavior introduced in #999
Fixes #1036
=> feat: revert the spine/toc nav order check to a WARNING

src/main/java/com/adobe/epubcheck/opf/XRefChecker.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties
This addresses the concern raised by @ShinyaTakami in #1056.
@ShinyaTakami can you please review?
=> remove 'ERROR' in the informative "under review" message

.travis.yml
Travis JDK downloads is quite brittle. See for instance the following community thread:
https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/6
Building on `trusty` is allegedly more stable (for JDK downloads) than building on `xenial`.
=> chore: set Travis to build on trusty

src/main/java/com/adobe/epubcheck/ops/OPSHandler.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java, src/test/resources/30/single/xhtml/invalid/url-checks_issue-708.xhtml
- fix #1034: make the message more genric ("Couldn't parse host…")
- fix #1079: don't report underscores used in the URL host part
- expand test `testValidateXHTMLUrlChecksInvalid`
=> fix: improve reporting of invalid URL host parts

pom.xml
CVE-2019-12402:
- Library: org.apache.commons:commons-compress
- Vulnerable versions: >= 1.15, < 1.19
- Patched version: 1.19
The file name encoding algorithm used internally in Apache Commons
Compress 1.15 to 1.18 can get into an infinite loop when faced with
specially crafted inputs. This can lead to a denial of service attack if
an attacker can choose the file names inside of an archive created by
Compress.
Fixes #1078
=> fix: upgrade commons-compress to v1.20 to remediate CVE-2019-12402

pom.xml
This adds an Automatic-Module-Name manifest entry in order to allow
epubcheck to be used in a modular context without having to depend
on an unstable generated module name.
Fix: https://github.com/w3c/epubcheck/issues/1128
=> Add an Automatic-Module-Name

src/main/resources/com/adobe/epubcheck/schema/30/epub-xhtml-30.sch, src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java, src/test/resources/30/single/xhtml/invalid/issue153.xhtml, src/test/resources/30/single/xhtml/invalid/title-empty.xhtml
Empty or whitespace-only `title` elements are disallowed in HTML:
https://html.spec.whatwg.org/#the-title-element
Nu HTML Checker checks this with Java Code, so it’s not exposed in
EPUBCheck (which only uses the Checkr’s schemas).
This change re-implements the check in Schematron.
Fixes #1093
=> feat: report empty `title` elements in XHTML Content Documents

src/main/java/com/adobe/epubcheck/bitmap/BitmapChecker.java
In some cases, 700KB .jpg can be about 8500x6000 pixels and BufferedImage consumes about 100MB.
So if you have a lot of such images you easily can get OOM. Do not sure why, but GC does not collect old BufferedImage during single validation.
=> Avoid usage of BufferedImage to avoid OutOfMemoryError

src/main/java/com/adobe/epubcheck/ops/OPSChecker.java, src/main/java/com/adobe/epubcheck/xml/XMLValidators.java, src/main/resources/com/adobe/epubcheck/schema/20/rng/ops20-svg.nvdl, src/main/resources/com/adobe/epubcheck/schema/20/rng/ops20.nvdl
Fixes #1147 by adding an NVDL script similar to the EPUB 3 version to remove foreign namespaced elements and attributes before dispatching to the SVG 1.1 RNG.
I also copied the allowForeignNS mode into the XHTML NVDL schema to do the same for embedded SVGs.
I haven't added any tests to this PR as I don't want to write them using the old format. I'll open a separate PR later with some tests using the new. I did test against the second file in issue #1147, modified to also embed an SVG, and didn't get the reported errors anymore.
=> Allow foreign namespaced elements and attributes in EPUB 2 SVGs

src/main/resources/com/adobe/epubcheck/schema/30/mod/epub-xhtml.rnc, src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/embed.rnc, src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/structural.rnc
This fixes #1019 and #1141 by overriding the section attrs definition to allow doc-epigraph.
I also discovered that doc-cover is not allowed on img, so it adds an override for that. It's not currently listed in the ARIA in HTML document.
I couldn't find any more elegant way to add these semantics, as there's no way to inject them into the allowed roles as the lists are element-specific.
Both these patches should only be temporary, though, as the HTML schemas should eventually be updated to allow them.
=> Allow doc-epigraph and doc-cover

src/main/java/com/adobe/epubcheck/vocab/AccessibilityVocab.java, src/test/java/com/adobe/epubcheck/opf/OPFCheckerTest.java, src/test/resources/30/single/opf/valid/vocab-a11y-credentials-in-link.opf
=> fix: allow 'a11y:certifierCredential' as a link

src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/structural.rnc
This should fully match us up with the ARIA in HTML doc again.
=> add doc-dedication to aside roles

src/test/resources/epub3/content-document-xhtml.feature, src/test/resources/epub3/files/content-document-xhtml/aria-roles-a-valid.xhtml, src/test/resources/epub3/files/content-document-xhtml/aria-roles-aside-valid.xhtml, src/test/resources/epub3/files/content-document-xhtml/aria-roles-footer-valid.xhtml, src/test/resources/epub3/files/content-document-xhtml/aria-roles-h1-h6-valid.xhtml, src/test/resources/epub3/files/content-document-xhtml/aria-roles-header-valid.xhtml, src/test/resources/epub3/files/content-document-xhtml/aria-roles-hr-valid.xhtml, src/test/resources/epub3/files/content-document-xhtml/aria-roles-img-valid.xhtml, src/test/resources/epub3/files/content-document-xhtml/aria-roles-li-valid.xhtml, src/test/resources/epub3/files/content-document-xhtml/aria-roles-nav-valid.xhtml, src/test/resources/epub3/files/content-document-xhtml/aria-roles-section-valid.xhtml
Adds tests for each element in the ARIA in HTML doc that has a restricted set of allowed DPUB-ARIA roles.
Setting this up as a separate PR from #1112 as the test for doc-epigraph will fail until merged with the new code base.
=> Add DPUB-ARIA role tests

src/main/resources/com/adobe/epubcheck/schema/30/package-30.sch, src/test/resources/epub3/files/package-document/mediaoverlays-active-class-refines-error.opf, src/test/resources/epub3/files/package-document/mediaoverlays-playback-active-class-refines-error.opf, src/test/resources/epub3/mediaoverlays-package-document.feature
A couple of minor schema updates and tests for the ["must not" in s. 3.4](https://www.w3.org/publishing/epub/epub-mediaoverlays.html#sec-docs-assoc-style).
=> Test and check playback classes do not have refines attribute

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/overlay/ClipTime.java, src/main/java/com/adobe/epubcheck/overlay/OverlayHandler.java, src/main/java/com/adobe/epubcheck/overlay/SmilClock.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/main/resources/com/adobe/epubcheck/schema/30/media-overlay-30.sch, src/test/resources/epub3/files/mediaoverlays-document/clip-times-equal-error.smil, src/test/resources/epub3/files/mediaoverlays-document/clipBegin-after-clipEnd-error.smil, src/test/resources/epub3/files/mediaoverlays-document/clock-value-partial-syntax-valid.smil, src/test/resources/epub3/mediaoverlays-smil-document.feature
This PR adds better support for the processing of the `clipBegin`/`clipEnd` attributes as follows:
- Adds the DAISY SmilClock class for processing SMIL clock values
- Moves the test of `clipBegin`/`clipEnd` equality into Java code so it isn't a simple string comparison
- Adds a test that `clipBegin` is not temporally after `clipEnd`
- Adds and updates associated tests
=> Improve handling of audio clip times in media overlay documents

src/main/java/com/adobe/epubcheck/overlay/OverlayHandler.java, src/test/resources/epub3/files/epub/package-manifest-prop-remote-resource-overlays-error/EPUB/chapter_001_overlay.smil, src/test/resources/epub3/files/epub/package-manifest-prop-remote-resource-overlays-error/EPUB/content_001.xhtml, src/test/resources/epub3/files/epub/package-manifest-prop-remote-resource-overlays-error/EPUB/nav.xhtml, src/test/resources/epub3/files/epub/package-manifest-prop-remote-resource-overlays-error/EPUB/package.opf, src/test/resources/epub3/files/epub/package-manifest-prop-remote-resource-overlays-error/META-INF/container.xml, src/test/resources/epub3/files/epub/package-manifest-prop-remote-resource-overlays-error/mimetype, src/test/resources/epub3/package-publication.feature
This PR makes the following changes:
- adds a check on audio start tags to flag when there are remote resource references
- adds a check on the end of the smil document to verify that remote-resources is specified on the package item declaration
Also adds a test to report an error when the property is not set.
=> Check remote-resources property is set for media overlay documents

src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java, src/test/resources/epub-dictionaries/dictionaries-publication.feature, src/test/resources/epub-dictionaries/files/epub/glossary-single-package-property-not-defined-error/EPUB/content_001.xhtml, src/test/resources/epub-dictionaries/files/epub/glossary-single-package-property-not-defined-error/EPUB/nav.xhtml, src/test/resources/epub-dictionaries/files/epub/glossary-single-package-property-not-defined-error/EPUB/package.opf, src/test/resources/epub-dictionaries/files/epub/glossary-single-package-property-not-defined-error/EPUB/search.xml, src/test/resources/epub-dictionaries/files/epub/glossary-single-package-property-not-defined-error/META-INF/container.xml, src/test/resources/epub-dictionaries/files/epub/glossary-single-package-property-not-defined-error/mimetype, src/test/resources/epub-dictionaries/files/epub/glossary-single-valid/EPUB/content_001.xhtml, src/test/resources/epub-dictionaries/files/epub/glossary-single-valid/EPUB/nav.xhtml, src/test/resources/epub-dictionaries/files/epub/glossary-single-valid/EPUB/package.opf, src/test/resources/epub-dictionaries/files/epub/glossary-single-valid/EPUB/search.xml, src/test/resources/epub-dictionaries/files/epub/glossary-single-valid/META-INF/container.xml, src/test/resources/epub-dictionaries/files/epub/glossary-single-valid/mimetype, src/test/resources/epub3/package-publication.feature
The `glossary` manifest item property is defined in the EPUB dictionaries
and Glossaries 1.0 specification:
http://idpf.org/epub/dict/epub-dict.html#sec-2.5.3
This fix allows the property to be defined on XHTML manifest items when
the content contains an element with a `glossary` `epub:type` attribute.
Fixes #1170
=> fix: allow the 'glossary' manifest item property

src/main/java/com/adobe/epubcheck/reporting/CheckerMetadata.java, src/main/java/com/adobe/epubcheck/util/PathUtil.java, src/test/java/com/adobe/epubcheck/util/PathUtilTest.java
The previous implementation of the `removeWorkingDirectory` utility
method was quite brutal and replaced all occurences of the "user.dir"
system property in paths, even when found in the middle of the path.
The new implementation only replaces the user directory when it occurs
at the beginning of the path, and does nothing when the user directory
is set to the root directory ("/").
Tests included.
Fixes #1181
=> fix: remove the user directory only at the start of paths (in messages)

src/main/java/com/adobe/epubcheck/ctc/FileLinkSearch.java, src/test/resources/epub3/content-publication.feature, src/test/resources/epub3/files/epub/content-xhtml-link-to-local-file-escaped-valid/EPUB/content_001.xhtml, src/test/resources/epub3/files/epub/content-xhtml-link-to-local-file-escaped-valid/EPUB/nav.xhtml, src/test/resources/epub3/files/epub/content-xhtml-link-to-local-file-escaped-valid/EPUB/package.opf, src/test/resources/epub3/files/epub/content-xhtml-link-to-local-file-escaped-valid/META-INF/container.xml, src/test/resources/epub3/files/epub/content-xhtml-link-to-local-file-escaped-valid/mimetype
Fix the regex used to report "file:" hyperlinks as `HTM-053` (informative)
to only consider HTML elements and not plain text.
This regex-based parsing is still brittle, but we'll refactor this whole
package later. For now this simple fix will do.
Fixes #1182
=> fix: do not treat escaped <a> elements as hyperlinks in HTM-053

src/main/java/com/adobe/epubcheck/css/CSSHandler.java, src/test/resources/epub3/content-publication.feature, src/test/resources/epub3/files/epub/content-css-url-fragment-valid/EPUB/content_001.xhtml, src/test/resources/epub3/files/epub/content-css-url-fragment-valid/EPUB/nav.xhtml, src/test/resources/epub3/files/epub/content-css-url-fragment-valid/EPUB/package.opf, src/test/resources/epub3/files/epub/content-css-url-fragment-valid/EPUB/style.css, src/test/resources/epub3/files/epub/content-css-url-fragment-valid/META-INF/container.xml, src/test/resources/epub3/files/epub/content-css-url-fragment-valid/mimetype
CSS defines a special processing for the resolution of fragment-only URLs.
These are resolved based on the HTML document, not relative to the
stylesheet.
For example, an SVG filter inlined in the HTML can be refered in CSS as:
```
* {
filter: url(#filter);
}
```
Such fragment-only URLs were previously reported as errors in EPUBCheck,
since the related fragment could not be found in the CSS document!
This change fixes the issue by ignoring fragment-only URLs in CSS. In
other words, these URLs will not be registered to the XRefChecker.
Fixes #1198
=> fix: do not report fragment-only CSS URLs

src/main/resources/com/adobe/epubcheck/schema/30/package-30.rnc, src/test/resources/epub3/files/package-document/lang-empty-valid.opf, src/test/resources/epub3/package-document.feature
An empty `xml:lang` attribute can explicitly indicate that the content
does not inherit the context language.
Fixes #777
=> fix: allow empty `xml:lang` attributes in Package Documents

src/main/java/com/adobe/epubcheck/nav/NavChecker.java, src/test/resources/epub-indexes/indexes-publication.feature
This fix removes the index-specific schemas when checking the Navigation
Document.
It is probably too simple, a better implementation would only do so if
the Nav Doc is not in the spine or is not the only Content Document in
the spine, but there is no easy way to check that latter condition in
the NavChecker.
The fix is a reasonable compromise, as a false-negative (the Nav Doc
**must** have index content when it is the unique Content Document) should
be pretty rare, and is always better than a false-positive.
Fixes #1122
=> fix: do not require the Navigation Document to have an index

.travis.yml
Would be interested to know why travis caching hasn't been enabled in this repository. Thank you.
=> Enable caching for travis

src/main/resources/com/adobe/epubcheck/schema/30/package-30.sch, src/test/resources/epub3/files/package-document/metadata-meta-role-refines-disallowed-error.opf, src/test/resources/epub3/files/package-document/metadata-meta-role-valid.opf, src/test/resources/epub3/package-document.feature
This PR proactively implements the relaxed EPUB 3.3 rules for the `role` property, to fix #1230.
=> feat: allow multiple roles for creator, contributor, and publisher

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/test/resources/epub3/mediaoverlays-publication.feature
This PR demotes MED-015 to a USAGE. EPUB 3.3 will no longer required that Media Overlays are in content order. 
This proactively implements #1225, and goes a little further to what was proposed in the discussion by using `USAGE` instead of a `WARNING`.
=> feat: do not report Media Overlays ordering mismatch

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/opf/OPFChecker30.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/resources/epub3/files/package-document/item-href-with-fragment-error.opf, src/test/resources/epub3/package-document.feature
Manifest `item` URLs that have a fragment are now reported as `OPF-091` (new check).
Fix #1250
=> feat: check that item URLs have no fragment

src/main/resources/com/adobe/epubcheck/schema/30/package-30.sch, src/test/resources/epub3/files/package-document/metadata-refines-not-a-fragment-warning.opf, src/test/resources/epub3/files/package-document/metadata-refines-not-relative-error.opf, src/test/resources/epub3/package-document.feature
- `refines` MUST be a relative URL
- `refines` SHOULD refer to a Publication Resource by ID
- `refines` MUST point to an existing ID when it is a fragment-only URL
Fix #1226
=> feat: update checking of the Package Document 'refines' attribute

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/opf/OPFHandler30.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/main/resources/com/adobe/epubcheck/schema/30/package-30.rnc, src/test/resources/epub3/files/package-document/attr-lang-not-well-formed-error.opf, src/test/resources/epub3/files/package-document/attr-lang-whitespace-error.opf, src/test/resources/epub3/files/package-document/link-hreflang-not-well-formed-error.opf, src/test/resources/epub3/files/package-document/link-hreflang-whitespace-error.opf, src/test/resources/epub3/files/package-document/metadata-language-empty-error.opf, src/test/resources/epub3/files/package-document/metadata-language-not-well-formed-error.opf, src/test/resources/epub3/package-document.feature
In Package Document, the language tags appearing in the elements or attributes below MUST be well-formed according to BCP47:
- `xml:lang` attribute
- `hreflang` attribute
- `dc:language` element
For these values:
- the schema now only do basic datatype check (string, non-empty value when relevant)
- the well-formedness is checked with Java’s Locale.Builder#setLanguageTag() API
- a new check (OPF-092) is reported when an ill-formed value is found
See https://docs.oracle.com/javase/8/docs/api/java/util/Locale.Builder.html#setLanguageTag-java.lang.String-
Fix #1221
Close #702
=> feat: new check (OPF-092) for language tags well-formedness

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/xml/XMLParser.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/resources/epub3/content-document-xhtml.feature, src/test/resources/epub3/files/content-document-xhtml/attrs-custom-ns-reserved-error.xhtml
EPUB 3.3 disallows "w3.org" and "idpf.org" in domains of XHTML custom attribute namespaces.
Fix #1190
=> feat: report reserved string in XHTML custom attribute namespaces

src/main/java/com/adobe/epubcheck/opf/XRefChecker.java, src/test/resources/epub3/navigation-publication.feature
=> fix: remove "under review" notice for toc nav ordering warning

src/test/resources/epub3/files/epub/package-manifest-prop-scripted-declared-but-unnecessary-error/EPUB/content_001.xhtml
EPUBCheck already handled data block scripts properly (see 05e5ac2351616f2b65ddfb7bf64ad54d972ed5c8)
But the test that reported an unnecessary `scripted` property did not include a data block to be sure.
Fix #1216
=> test: 'scripted' property is disallowed for data blocks

src/main/resources/com/adobe/epubcheck/schema/30/epub-nav-30.sch, src/test/resources/epub3/files/navigation-document/nav-type-missing-not-restricted-valid.xhtml, src/test/resources/epub3/navigation-document.feature
EPUB 3.3, allows `nav` elements with no `epub:type` attribute in the Navigation Document, without any content model restrictions.
This commit:
- update the schema to discard the previously-reported warning
- update the tests
Fix #1222
=> feat: ignore Nav Doc `nav` elements with no epub:type

src/main/java/com/adobe/epubcheck/opf/XRefChecker.java, src/test/resources/epub3/navigation-publication.feature
This commit:
- removes the call to check the page list reading order
- keeps the checking code, as well as NAV-011
- update tests
Fix #1237
=> feat: page-list nav does not have to match reading order

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/resources/epub3/content-document-xhtml.feature, src/test/resources/epub3/content-publication.feature, src/test/resources/epub3/files/content-document-xhtml/discouraged-base-warning.xhtml, src/test/resources/epub3/files/content-document-xhtml/discouraged-embed-warning.xhtml, src/test/resources/epub3/files/content-document-xhtml/discouraged-rp-warning.xhtml, src/test/resources/epub3/files/epub/content-xhtml-svg-reference-valid/EPUB/content_001.xhtml
EPUB 3.3 discourages the use of the following elements:
- `base`
- `rp`
- `embed`
This commits:
- adds a new check HTM-055 to report all uses of discouraged elements
- add tests for discouraged constructs
- tweak existing tests that used discouraged constructs
Fix #1271
=> feat: check discouraged HTML elements (base, rp, embed)

src/main/resources/com/adobe/epubcheck/schema/30/epub-nav-30.sch, src/test/resources/epub3/files/navigation-document/nav-landmarks-nested-warning.xhtml, src/test/resources/epub3/files/navigation-document/nav-page-list-nested-warning.xhtml, src/test/resources/epub3/navigation-document.feature
EPUB 3.3 clarifies that authors should not use nested lists for 'page-list' and 'landmarks' nav.
This commit:
- reports a schema warning for nested 'page-list' or 'landmarks' nav (implemented in schematron)
- add tests
Fix #1279
=> feat: check that 'page-list' and 'landmarks' nav are flat lists

src/main/java/com/adobe/epubcheck/opf/XRefChecker.java, src/test/resources/epub3/files/epub/resources-remote-audio-object-valid/EPUB/content_001.xhtml, src/test/resources/epub3/files/epub/resources-remote-audio-object-valid/EPUB/nav.xhtml, src/test/resources/epub3/files/epub/resources-remote-audio-object-valid/EPUB/package.opf, src/test/resources/epub3/files/epub/resources-remote-audio-object-valid/META-INF/container.xml, src/test/resources/epub3/files/epub/resources-remote-audio-object-valid/mimetype, src/test/resources/epub3/files/epub/resources-remote-video-object-valid/EPUB/content_001.xhtml, src/test/resources/epub3/files/epub/resources-remote-video-object-valid/EPUB/nav.xhtml, src/test/resources/epub3/files/epub/resources-remote-video-object-valid/EPUB/package.opf, src/test/resources/epub3/files/epub/resources-remote-video-object-valid/META-INF/container.xml, src/test/resources/epub3/files/epub/resources-remote-video-object-valid/mimetype, src/test/resources/epub3/resources-publication.feature
Previously, EPUBCheck only allowed remote resources when they were used in elements we knew allowed remote resources (e.g. audio, video, font declaration).
This commit improves this check by first checking that the resource media type allows remote resources, regardless of where the resource is used.
Fix #1288
=> feat: loosen restriction on where remote resources can be referenced

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/test/resources/epub3/navigation-publication.feature, src/test/resources/epub3/package-publication.feature
EPUB does not require that the navigation document (or NCX in EPUB 2.0.1) links to all the documents listed in the spine.
EPUBCheck reported this as USAGE messages (`OPF-059` and `OPF-058`), which are now suppressed.
Note: this change will only be effective when the checks of the `ctc` package  are disabled.
=> feat: no longer check that navigation links to all spine items

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/test/resources/epub3/resources-publication.feature
The `ctc` package contained checks that looked at javascript content and tried to detect suspicious or potentially problematic usage patterns.
This check were necessarily incomplete, and based on regex pattern matching, so inherently open to many false positives or false negatives.
This change  suppresses all of them. Inspecting javascript is not possible and out of scope for EPUBCheck.
Note: this change will only be effective when the checks of the `ctc` package  are disabled.
=> feat: disable usage reports related to javascript content

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/ops/OPSHandler.java, src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java, src/test/resources/epub3/content-document-xhtml.feature, src/test/resources/epub3/content-publication.feature, src/test/resources/epub3/files/content-document-xhtml/link-rel-stylesheet-alternate-no-title-error.xhtml
`HTM-046` and `HTM-048` check that HTML fixed-layout documents
have viewport metadata.
This change reimplements these checks in `OPSHandler30` so that the
`ctc` package can be disabled.
RSC-018 was introduced in the `ctc` package to check the images
specified in the MathML `altimg` attribute exist in the container.
EPUBCheck already has an error code  for missing resources, namely `RSC-018`.
This  change adds a check for the `altimg` in OPSHandler, and suppresses
`RSC-018`.
`HTM-053` is an INFO-level message that reports links to local files
(absolute `file` URLs).
This check is moved to the core OPSHandler checks, so we can
safely disable the `ctc` package.
Note: these changes will only be effective when the `ctc` package is removed.
=> feat: re-implement relevant checks from the `ctc` package in core handlers

src/main/java/com/adobe/epubcheck/opf/OPFHandler30.java, src/main/java/com/adobe/epubcheck/vocab/RenditionVocabs.java, src/main/resources/com/adobe/epubcheck/schema/30/package-30.sch, src/test/resources/epub3/08-layout/layout.feature, src/test/resources/epub3/D-vocabularies/files/rendition-property-unknown-error.opf, src/test/resources/epub3/D-vocabularies/package-rendering-vocab.feature
- deprecated properties are now reported as `OPF-086`, like for other deprecated properties, instead of `RSC-017`. This means the check relies on the `Property#isDeprecated` facility, instead of custom Schematron code.
- deprecated property value is checked in custom Java code the `OPFHandler30#processMeta()` method.
- verify that custom properties cannot be defined using the reserved "rendition" prefix. A new feature file is added for this single test, to match the spec section ordering.
Fix #1327
=> feat: update checking of the package rendering vocabulary

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/opf/XRefChecker.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/resources/epub3/03-resources/files/resources-remote-audio-sources-foreign-valid/EPUB/content_001.xhtml, src/test/resources/epub3/03-resources/files/resources-remote-audio-sources-valid/EPUB/content_001.xhtml, src/test/resources/epub3/03-resources/files/resources-remote-audio-sources-valid/EPUB/package.opf, src/test/resources/epub3/03-resources/files/resources-remote-audio-valid/EPUB/package.opf, src/test/resources/epub3/03-resources/files/resources-remote-not-https-warning/EPUB/content_001.xhtml, src/test/resources/epub3/03-resources/files/resources-remote-not-https-warning/EPUB/nav.xhtml, src/test/resources/epub3/03-resources/files/resources-remote-not-https-warning/EPUB/package.opf, src/test/resources/epub3/03-resources/files/resources-remote-not-https-warning/EPUB/style.css, src/test/resources/epub3/03-resources/files/resources-remote-not-https-warning/META-INF/container.xml, src/test/resources/epub3/03-resources/files/resources-remote-not-https-warning/mimetype, src/test/resources/epub3/03-resources/files/resources-remote-video-valid/EPUB/content_001.xhtml, src/test/resources/epub3/03-resources/files/resources-remote-video-valid/EPUB/package.opf, src/test/resources/epub3/03-resources/resources.feature, src/test/resources/epub3/05-package-document/files/package-manifest-prop-remote-resource-undeclared-error/EPUB/content_001.xhtml, src/test/resources/epub3/05-package-document/files/package-manifest-prop-remote-resource-undeclared-error/EPUB/package.opf, src/test/resources/epub3/05-package-document/files/package-remote-audio-in-overlays-missing-property-error/EPUB/chapter_001_overlay.smil, src/test/resources/epub3/05-package-document/files/package-remote-audio-in-overlays-missing-property-error/EPUB/package.opf, src/test/resources/epub3/05-package-document/files/package-remote-audio-missing-property-error/EPUB/content_001.xhtml, src/test/resources/epub3/05-package-document/files/package-remote-audio-missing-property-error/EPUB/package.opf, src/test/resources/epub3/05-package-document/files/package-remote-audio-sources-undeclared-error/EPUB/content_001.xhtml, src/test/resources/epub3/05-package-document/files/package-remote-audio-sources-undeclared-error/EPUB/package.opf, src/test/resources/epub3/05-package-document/files/package-remote-audio-undeclared-error/EPUB/content_001.xhtml, src/test/resources/epub3/06-content-document/files/content-xhtml-video-poster-media-type-error/EPUB/content_001.xhtml, src/test/resources/epub3/06-content-document/files/content-xhtml-video-poster-media-type-error/EPUB/package.opf
This commit introduces a new check `RSC-031` (warning) that is reported when a reference to a remote resource (font, audio, video) is not using HTTPS.
Fix #1337
=> feat: warn about non-HTTPS remote resource references

src/main/java/com/adobe/epubcheck/opf/XRefChecker.java
Unnecessary recursion was causing StackOverflowError with large package documents.
Fix #1358, Close #1356.
Co-Authored-By: Daniel Persson <kalaspuffar@users.noreply.github.com>
=> fix: remove recursion in reading order checks

src/main/java/com/adobe/epubcheck/css/CSSChecker.java, src/main/java/com/adobe/epubcheck/css/CSSHandler.java, src/test/resources/epub3/05-package-document/files/package-remote-font-in-inline-css-missing-property-error/EPUB/content_001.xhtml, src/test/resources/epub3/05-package-document/files/package-remote-font-in-inline-css-missing-property-error/EPUB/nav.xhtml, src/test/resources/epub3/05-package-document/files/package-remote-font-in-inline-css-missing-property-error/EPUB/package.opf, src/test/resources/epub3/05-package-document/files/package-remote-font-in-inline-css-missing-property-error/META-INF/container.xml, src/test/resources/epub3/05-package-document/files/package-remote-font-in-inline-css-missing-property-error/mimetype, src/test/resources/epub3/05-package-document/files/package-remote-resource-and-inline-css-valid/EPUB/content_001.xhtml, src/test/resources/epub3/05-package-document/files/package-remote-resource-and-inline-css-valid/EPUB/nav.xhtml, src/test/resources/epub3/05-package-document/files/package-remote-resource-and-inline-css-valid/EPUB/package.opf, src/test/resources/epub3/05-package-document/files/package-remote-resource-and-inline-css-valid/META-INF/container.xml, src/test/resources/epub3/05-package-document/files/package-remote-resource-and-inline-css-valid/mimetype, src/test/resources/epub3/05-package-document/package-document.feature
`OPF-018` checks that the `remote-resources` property is not defined if no remote resource was found.
Prior to this PR, it was incorrectly reported when an XHTML content document carrying the property also contained inline CSS: the CSS checker thought that the property was not required since no remote resource was found in the CSS itself.
This commit fixes that bug by only checking `OPF-018` for standalone CSS documents.
Fix #1335
=> fix: OPF-018 was incorrectly reported with inline CSS

pom.xml
Bumps imageio-jpeg version to 3.9.4.
Fix #1336
=> fix: fix CVE-2021-23792 vulnerability from imageio-jpeg

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/common.rnc, src/test/resources/epub3/06-content-document/content-document-xhtml.feature, src/test/resources/epub3/06-content-document/files/img-src-empty-error.xhtml
This change effectively removes `HTM-008` by integrating (the emptyness part of) the check for valid non-empty URL in the RelaxNG schema.
=> feat: report empty URL as a schema error instead of HTM-008

pom.xml, src/main/java/com/adobe/epubcheck/xml/XMLValidator.java, src/main/java/org/idpf/epubcheck/util/saxon/ColumnNumberFunction.java, src/main/java/org/idpf/epubcheck/util/saxon/Int64ValueSequence.java, src/main/java/org/idpf/epubcheck/util/saxon/LineNumberFunction.java, src/main/java/org/idpf/epubcheck/util/saxon/SaxonSchemaReaderFactory.java, src/main/java/org/idpf/epubcheck/util/saxon/SystemIdFunction.java, src/main/resources/META-INF/services/com.thaiopensource.validate.SchemaReaderFactory, src/test/resources/epub3/05-package-document/files/collection-role-url-valid.opf
This commit updates the Saxon-HE dependency to version 11.4.
It refactors the Saxon-related code as follows:
- update the function+registration code to the latest API changes
- extract the Saxon schema reader factory (used by Jing) in its own class
- the Saxon schema reader factory is made available to Jing via the SPI mechanism (declared in `META-INF/services/com.thaiopensource.validate.SchemaReaderFactory`). This notably allows Jing to find and use our factory for both Schematron and NVDL.
- the Saxon schema reader factory no longer extends Jing's `NewSaxonSchemaReaderFactory`, which set the feature "XSLT_VERSION" to "2.0" and caused a Warning to be issued by Saxon 11.
Fix #1341
=> feat: update Saxon library to v11.4

src/main/resources/com/adobe/epubcheck/schema/30/package-30.rnc, src/test/resources/epub3/05-package-document/package-document.feature
This change is quite transparent and does not impact test, but makes the schema typing more consistent.
Also adds a spec ref tag to the valid test case.
Fix #1385
=> refactor: set 'hreflang' schema type to 'datatype.languagecode'

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/test/resources/epub3/03-resources/resources.feature, src/test/resources/epub3/06-content-document/content-document-xhtml.feature
The HTML discouraged constructs section is non-normative. This PR now reports use of these constructs as a usage message instead of a warning.
The severity level of `HTM-055` is now `USAGE`.
Fix #1387.
=> fix: report HTML discouraged constructs as "usage"

docs/messages/index.html
The on page link for message code was incorrect.  Had #messages-reference and should be #message-codes l:200
=> Correct link to #message-codes

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/opf/OPFChecker30.java, src/main/java/com/adobe/epubcheck/opf/OPFHandler30.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/resources/epub3/05-package-document/files/link-to-embedded-resource-valid/EPUB/content_001.xhtml, src/test/resources/epub3/05-package-document/files/link-to-embedded-resource-valid/EPUB/nav.xhtml, src/test/resources/epub3/05-package-document/files/link-to-embedded-resource-valid/EPUB/package.opf, src/test/resources/epub3/05-package-document/files/link-to-embedded-resource-valid/META-INF/container.xml, src/test/resources/epub3/05-package-document/files/link-to-embedded-resource-valid/mimetype, src/test/resources/epub3/05-package-document/files/link-to-package-document-id-error.opf, src/test/resources/epub3/05-package-document/files/link-to-spine-item-valid.opf, src/test/resources/epub3/05-package-document/package-document.feature
This commit checks that the linked resource is not in the spine before
reporting `OPF-067` ("The resource "…" must not be listed both as a
"link" element in the package metadata and as a manifest item.").
Effectively, this allows package links to publication resources in the
two cases identified in the EPUB 3.3 specification:
> Resources referenced from the link element are publication resources
> only when they are:
> - referenced from the spine; or
> - included or embedded in an EPUB content document
Fix #1454
This commit introduces a new error message (`OPF-098`) to report `href` attributes
containing a URL to package document elements.
This implements a check for the following specification statement:
> The URL string MUST NOT reference resources via elements in the package document
=> improve checks of package links

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/opf/OPFChecker.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/resources/epub3/05-package-document/files/manifest-self-referencing-error.opf, src/test/resources/epub3/05-package-document/files/manifest-self-referencing-error/EPUB/content_001.xhtml, src/test/resources/epub3/05-package-document/files/manifest-self-referencing-error/EPUB/nav.xhtml, src/test/resources/epub3/05-package-document/files/manifest-self-referencing-error/EPUB/package.opf, src/test/resources/epub3/05-package-document/files/manifest-self-referencing-error/META-INF/container.xml, src/test/resources/epub3/05-package-document/files/manifest-self-referencing-error/mimetype, src/test/resources/epub3/05-package-document/package-document.feature
This commit adds a new check, reported as `OPF-099` (error), to verify that the package document `manifest` does not include an `item` element that refers to the package document itself.
This statement was apparently not checked by EPUBCheck previously. Worse, the code was entering an infinite loop, as the package document checker was creating a new checker for itself, recursively.
Fix #1453
=> feat: check that the manifest is not self-referencing

src/main/java/com/adobe/epubcheck/messages/DefaultSeverities.java, src/main/java/com/adobe/epubcheck/messages/MessageId.java, src/main/java/com/adobe/epubcheck/xml/HTMLUtils.java, src/main/java/com/adobe/epubcheck/xml/handlers/PreprocessingDefaultHandler.java, src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties, src/test/resources/epub3/06-content-document/content-document-xhtml.feature, src/test/resources/epub3/06-content-document/files/data-attr-invalid-error.xhtml
According to HTML:
> A custom data attribute is an attribute in no namespace whose name
> starts with the string "data-", has at least one character after the
> hyphen, is XML-compatible, and contains no ASCII upper alphas.
This commit reports invalid `data-*` attributes as errors with a new error code, `HTM-061`.
This should be ideally delegated to validator.nu, but we add this check until we fully integrate the HTML checker.
Close #1107
=> feat: check "data-*" attributes name restrictions

src/main/resources/com/adobe/epubcheck/schema/30/edupub/edu-structure.sch, src/main/resources/com/adobe/epubcheck/schema/30/epub-nav-30.sch, src/test/resources/epub3/07-navigation-document/files/content-model-a-multiple-images-valid.xhtml, src/test/resources/epub3/07-navigation-document/files/content-model-li-label-multiple-images-valid.xhtml, src/test/resources/epub3/07-navigation-document/navigation-document.feature
A bug in the Schematron XPath expressions caused a fatal error to be reported when nav doc items contained multiple images.
This commit fix the relevant expressions by using the `string-join` function instead of `concat`, allowing to join arbitrary sequences of text nodes.
Fix #1476
=> fix: allow nav items containing multiple images

src/main/java/com/adobe/epubcheck/opf/OPFHandler30.java, src/main/java/com/adobe/epubcheck/vocab/PackageVocabs.java, src/test/resources/epub3/05-package-document/files/item-property-cover-image-webp-valid.opf, src/test/resources/epub3/05-package-document/package-document.feature
Prior to this commit, we used a hardcoded list of MIME types to check that the 'cover-image' property was used on images (CMT only).
Now, we only check that the MIME type stars with 'image/'.
Fix #1484
=> fix: allow the 'cover-image' property on WebP images

src/main/java/org/w3c/epubcheck/core/references/ResourceReferencesChecker.java, src/test/resources/epub3/06-content-document/content-document-xhtml.feature, src/test/resources/epub3/06-content-document/files/object-pdf-fragment-valid/EPUB/content_001.xhtml, src/test/resources/epub3/06-content-document/files/object-pdf-fragment-valid/EPUB/nav.xhtml, src/test/resources/epub3/06-content-document/files/object-pdf-fragment-valid/EPUB/package.opf, src/test/resources/epub3/06-content-document/files/object-pdf-fragment-valid/META-INF/container.xml, src/test/resources/epub3/06-content-document/files/object-pdf-fragment-valid/mimetype
=> fix: do not check fragment identifiers on PDF references

src/main/java/org/w3c/epubcheck/util/microsyntax/ViewportMeta.java, src/test/resources/epub3/08-layout/files/content-fxl-xhtml-viewport-float-valid/EPUB/content_001.xhtml, src/test/resources/epub3/08-layout/files/content-fxl-xhtml-viewport-float-valid/EPUB/nav.xhtml, src/test/resources/epub3/08-layout/files/content-fxl-xhtml-viewport-float-valid/EPUB/package.opf, src/test/resources/epub3/08-layout/files/content-fxl-xhtml-viewport-float-valid/META-INF/container.xml, src/test/resources/epub3/08-layout/files/content-fxl-xhtml-viewport-float-valid/mimetype, src/test/resources/epub3/08-layout/layout.feature
The spec only says dimensions must be a "positive number" (or keyword), it does not specifically forbid decimal values.
Fix #1481
=> fix: allow decimal viewport dimensions in fixed-layout

src/main/java/com/adobe/epubcheck/ocf/OCFContainer.java, src/main/java/org/w3c/epubcheck/core/references/URLChecker.java, src/main/java/org/w3c/epubcheck/util/url/URLUtils.java, src/test/resources/epub3/04-ocf/files/url-percent-encoded-valid/EPUB/content&001.xhtml, src/test/resources/epub3/04-ocf/files/url-percent-encoded-valid/EPUB/nav.xhtml, src/test/resources/epub3/04-ocf/files/url-percent-encoded-valid/EPUB/package.opf, src/test/resources/epub3/04-ocf/files/url-percent-encoded-valid/META-INF/container.xml, src/test/resources/epub3/04-ocf/files/url-percent-encoded-valid/mimetype, src/test/resources/epub3/04-ocf/ocf.feature
URLs were not normalized before performing existence checks. So percent-encoded URLs sometimes triggered `RSC-001` or `RSC-007` errors.
This commit introduces a new `normalize(URL)` method in the `URLUtils` class. Normalization is now used when checking a URL. This notably applies to resource and ID existence checks.
Important Note:
URL normalization is not well-defined. Some percent-encoding normalization is described in RFC3986, but is not defined in the URL standard. Also, normalization (as useful for EPUBCheck) is also dependent on the URL scheme.
The normalization we apply is quite naïve and might need to be improved in the future. It should however cover the majority of HTTP URL real-world scenarios.
Fix #1479
=> fix: normalize URLs before checking if the resources exist

src/main/java/com/adobe/epubcheck/opf/OPFHandler30.java, src/main/java/com/adobe/epubcheck/vocab/PackageVocabs.java, src/test/resources/epub3/D-vocabularies/files/metadata-meta-pageBreakSource-valid.opf, src/test/resources/epub3/D-vocabularies/meta-properties.feature
The ["pageBreakSource"](https://www.w3.org/publishing/a11y/page-source-id/#pageBreakSource) package metadata property is planned to be added to EPUB, after 3.3.
This commit allows this property to start incubating its use.
Fix #1491
=> feat: allow "pageBreakSource" package metadata (incubation)

src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java, src/main/java/org/w3c/epubcheck/core/references/ResourceReferencesChecker.java, src/test/resources/epub3/04-ocf/files/url-xhtml-cite-absolute-valid/EPUB/content_001.xhtml, src/test/resources/epub3/04-ocf/files/url-xhtml-cite-absolute-valid/EPUB/nav.xhtml, src/test/resources/epub3/04-ocf/files/url-xhtml-cite-absolute-valid/EPUB/package.opf, src/test/resources/epub3/04-ocf/files/url-xhtml-cite-absolute-valid/META-INF/container.xml, src/test/resources/epub3/04-ocf/files/url-xhtml-cite-absolute-valid/mimetype, src/test/resources/epub3/04-ocf/ocf.feature
The resources referenced in `cite` attribute URLs are not publication resources.
This commit disables the publication-resource-specific URL checks for the `cite` attribute. For instance, the referenced document is not subject to resource location restrictions.
The URL is still registered in the reference registry, so that the existence of the underlying container resource is checked (for relative URLs).
Fix #1495
=> fix: allow remote URLs in HTML "cite" attributes

src/main/java/com/adobe/epubcheck/ocf/OCFZipResources.java, src/main/java/com/adobe/epubcheck/opf/ValidationContext.java, src/main/java/org/w3c/epubcheck/util/url/URLUtils.java
EPUBCheck used to work well with UNC paths in 4.x, but this was broken when implementing the new URL and container parsing code.
This commit improves the URL-to-File conversion:
- relies on `java.nio.file.Paths`
- utility methods are introduced in `URLUtils`
This was tested manually on Windows, but not in the test suite since this is largely OS-dependent.
Fix #1485
=> fix: support UNC paths (fix URL/File conversions)

src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java, src/test/resources/epub3/06-content-document/content-document-xhtml.feature, src/test/resources/epub3/06-content-document/files/dc-source-valid/EPUB/content_001.xhtml, src/test/resources/epub3/06-content-document/files/dc-source-valid/EPUB/nav.xhtml, src/test/resources/epub3/06-content-document/files/dc-source-valid/EPUB/package.opf, src/test/resources/epub3/06-content-document/files/dc-source-valid/META-INF/container.xml, src/test/resources/epub3/06-content-document/files/dc-source-valid/mimetype
The checks related to the HTML `source` element were run regardless of the element namespace, and with lack of protective coding. This caused an NPE when the markup contained `dc:source` elements.
This commit fixes the situation by:
- only applying `OPSHandler30` checks for the elements in the target namespace
- returning early when the `source` element preconditions aren't met, as these preconditions are checked by schema
Fix #1514
=> fix: `dc:source` element caused a NullPointerException

src/main/java/org/w3c/epubcheck/core/references/ResourceReferencesChecker.java, src/main/java/org/w3c/epubcheck/core/references/ResourceRegistry.java, src/test/resources/epub3/06-content-document/content-document-xhtml.feature, src/test/resources/epub3/06-content-document/files/content-xhtml-link-to-missing-id-in-nav-doc-error/EPUB/content_001.xhtml, src/test/resources/epub3/06-content-document/files/content-xhtml-link-to-missing-id-in-nav-doc-error/EPUB/nav.xhtml, src/test/resources/epub3/06-content-document/files/content-xhtml-link-to-missing-id-in-nav-doc-error/EPUB/package.opf, src/test/resources/epub3/06-content-document/files/content-xhtml-link-to-missing-id-in-nav-doc-error/META-INF/container.xml, src/test/resources/epub3/06-content-document/files/content-xhtml-link-to-missing-id-in-nav-doc-error/mimetype
When the `toc` nav of the navigation document contained links pointing to non-existing IDs, checking that links are in reading order caused a NullPointerException.
This commit fixes that by using a more defensive programming logic.
Fix #1516
=> fix: incorrect ID refs in toc nav caused a NullPointerException

src/main/java/com/adobe/epubcheck/tool/EpubChecker.java, src/test/java/com/adobe/epubcheck/tools/CommandLineTest.java
=> fix: make CLI return 0 for `--version` or `--help` options

src/main/resources/com/adobe/epubcheck/schema/20/rng/xhtml/edit.rng, src/test/resources/epub2/files/ops-document-xhtml/edit-block-content-valid.xhtml, src/test/resources/epub2/ops-content-document-xhtml.feature
See https://www.w3.org/TR/xhtml-modularization/abstract_modules.html#s_editmodule
Fix #1522
=> fix: allow flow content for XHTML 1.1 edit elements (EPUB 2.0.1)

src/main/java/com/adobe/epubcheck/xml/XMLEncodingSniffer.java, src/main/java/com/adobe/epubcheck/xml/XMLParser.java
On rare occasions, decoding UTF-8 documents caused a fatal error RSC-016 (`Invalid byte 2 of 4-byte UTF-8 sequence.`).
This was likely due to a bug in the Xerces XML parser decoding component, see https://issues.apache.org/jira/browse/XERCESJ-1668
As a workaround, we now read documents using the Java built-in UTF-8 decoder instead of Xerces's own decoder, by creating the SAX parsers' InputSource from an InputStreamReader instead of the raw InputStream.
Fixes #1548
=> fix: rare decoding error on UTF-8 documents

src/main/java/org/idpf/epubcheck/util/css/CssParser.java, src/test/java/org/idpf/epubcheck/util/css/CssParserTest.java, src/test/resources/css/custom-properties.css
Fix the built-in CSS parser to allow custom properties with empty values, as this is valid CSS.
See https://www.w3.org/TR/css-variables/#guaranteed-invalid
Fixes #1538
=> fix: allow CSS custom properties with no value

src/main/java/com/adobe/epubcheck/ocf/OCFContainer.java, src/main/java/org/w3c/epubcheck/core/references/ReferenceRegistry.java, src/test/resources/epub3/03-resources/files/data-url-with-unescaped-query-valid/EPUB/content_001.xhtml, src/test/resources/epub3/03-resources/files/data-url-with-unescaped-query-valid/EPUB/nav.xhtml, src/test/resources/epub3/03-resources/files/data-url-with-unescaped-query-valid/EPUB/package.opf, src/test/resources/epub3/03-resources/files/data-url-with-unescaped-query-valid/META-INF/container.xml, src/test/resources/epub3/03-resources/files/data-url-with-unescaped-query-valid/mimetype, src/test/resources/epub3/03-resources/resources.feature
A NullPointerException was raised on `data` URLs ending with a query-like string.
This was caused by a double-bug in Galimatias:
- removing the query-like string (as we do when registering references) with `URL#withQuery(null)` resulted in a hierarchical URL despite `data` URLs being non-hierarchical.
- such hybrid `data` URLs caused an NPE to be raised when canonicalized
We now add some check to not remove the query component on non-hierarchical URLs.
Also, `OCFContainer#isRemote(URL)` now returns false without further checks for `data` URLs.
Fixes #1536
=> fix: NullPointerException was raised on some data URLs

src/main/java/com/adobe/epubcheck/opf/OPFChecker.java, src/main/java/com/adobe/epubcheck/opf/OPFChecker30.java
=> fix: prevent some internal URLs from leaking in messages

pom.xml, src/main/java/com/adobe/epubcheck/ocf/OCFChecker.java, src/main/java/com/adobe/epubcheck/ocf/OCFZipResources.java, src/test/java/org/w3c/epubcheck/test/JSONReportAssertionSteps.java, src/test/java/org/w3c/epubcheck/test/XMLReportAssertionSteps.java, src/test/resources/reporting/xml-report.feature
Also enable test cases for the XML report.
=> fix: re[prt the container creation date

src/main/java/com/adobe/epubcheck/vocab/AccessibilityVocab.java, src/test/resources/epub-accessibility/accessibility.feature, src/test/resources/epub-accessibility/files/metadata-a11y-exemption-valid.opf
=> fix: recognize the `a11y:exemption` property

.github/workflows/maven-ci.yml
`actions/checkout@v2` and `actions/cache@v2` currently issue deprecation warnings during execution about deprecated Node.js version. 
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/cache@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v2, actions/cache@v2. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> chore: bump GitHub Action versions

pom.xml, src/main/java/com/adobe/epubcheck/api/EPUBLocation.java, src/main/java/com/adobe/epubcheck/api/MasterReport.java, src/main/java/com/adobe/epubcheck/reporting/CheckMessage.java, src/main/java/com/adobe/epubcheck/reporting/CheckerMetadata.java, src/main/java/com/adobe/epubcheck/reporting/CheckingReport.java, src/main/java/com/adobe/epubcheck/reporting/ItemMetadata.java, src/main/java/com/adobe/epubcheck/reporting/PublicationMetadata.java, src/main/java/com/adobe/epubcheck/util/JsonWriter.java
=> chore(deps): bump Jackson from 1.9.12 to 2.18.2

src/main/java/com/adobe/epubcheck/ocf/OCFContainer.java, src/test/resources/epub3/03-resources/files/mailto-url-valid/EPUB/content_001.xhtml, src/test/resources/epub3/03-resources/files/mailto-url-valid/EPUB/nav.xhtml, src/test/resources/epub3/03-resources/files/mailto-url-valid/EPUB/package.opf, src/test/resources/epub3/03-resources/files/mailto-url-valid/META-INF/container.xml, src/test/resources/epub3/03-resources/files/mailto-url-valid/mimetype, src/test/resources/epub3/03-resources/resources.feature
Fix a regression bug introduced in PR #1582, in the implementatiom of `OCFContainer#isRemote(URL)`.
The buggy implementation considered `mailto` URLs as local URLs. As a result, it reported an error as no matching local resource could be found in the container.
The new implementation says a URL is remote when it is not a `data` URL and is not the URL of a resource in the container.
Fix #1595
=> fix: `mailto` URLs were reported as missing resources

src/main/java/com/adobe/epubcheck/tool/EpubChecker.java, src/test/resources/cli/cli.feature
The message "No errors or warnings detected." was printed to `stdout` even when EPUBCheck was configured to print a JSON report to `stdout``, why caused the JSON output to be invalid. This commit fixes that by checking that JSON (or XML/XMP) is not being printed to `stdout` before writing this message.
Fixes #1603
=> fix: do not pollute stdout JSON with messages

src/main/java/org/idpf/epubcheck/util/css/CssGrammar.java, src/test/java/org/idpf/epubcheck/util/css/CssParserTest.java, src/test/resources/epub3/06-content-document/files/content-css-selectors-valid/EPUB/style.css
The CSS parser was raising an error when the selector list used by the `:has()` pseudo-class was not starting with an explicit relative combinator. This is now fixed and allowed.
Fix #1605, fix #1618
=> fix: allow CSS `has:(<selector>)` syntax

src/main/java/com/adobe/epubcheck/opf/OPFChecker30.java
=> fix: remove 'image/svg+xml' from font core media types

src/main/java/com/adobe/epubcheck/xml/HTMLUtils.java, src/main/java/com/adobe/epubcheck/xml/handlers/PreprocessingDefaultHandler.java, src/test/resources/epub3/06-content-document/content-document-xhtml.feature, src/test/resources/epub3/06-content-document/files/attrs-its-valid.xhtml
This change proactively allows ITS attributes in XHMTL content document, which is a new HTML extension planned in EPUB 3.4. See w3c/epub-specs#2732
The implementation naïvely removes the attributes when pre-processing the content sent to the validators. It does not check that the attributes are defined and conform to the requirements in ITS 2.0.
This is a first step in resolving #1616, to prevent EPUBCheck from totally rejecting ITS attributes.
=> feat: allow `its-*` attributes (ITS) in HTML
