w3c/epubcheck

- src/main/resources/com/adobe/epubcheck/messages/MessageBundle_de.properties
- src/main/resources/com/adobe/epubcheck/util/messages_de.properties
- src/main/resources/com/thaiopensource/validate/schematron/resources/Messages_de.properties
> Updated german messages for epubcheck 4.0

- src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java
- src/main/java/com/adobe/epubcheck/vocab/ComicsVocab.java
- src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java
- src/test/resources/30/expanded/valid/data-nav-regionbased-comics/EPUB/data-nav.xhtml
- src/test/resources/30/expanded/valid/data-nav-regionbased-comics/EPUB/package.opf
- src/test/resources/30/expanded/valid/data-nav-regionbased-comics/EPUB/page1.xhtml
- src/test/resources/30/expanded/valid/data-nav-regionbased-comics/EPUB/style.css
- src/test/resources/30/expanded/valid/data-nav-regionbased-comics/META-INF/container.xml
- src/test/resources/30/expanded/valid/data-nav-regionbased-comics/mimetype
> Allow new comics-related SSV terms

- src/main/resources/com/adobe/epubcheck/schema/20/rng/ncx-old.rng
- src/main/resources/com/adobe/epubcheck/schema/20/rng/ncx.rng
- src/test/java/com/adobe/epubcheck/api/Epub20CheckExpandedTest.java
- src/test/resources/20/expanded/invalid/ncx-pagetarget-type/EPUB/lorem.ncx
- src/test/resources/20/expanded/invalid/ncx-pagetarget-type/EPUB/lorem.opf
- src/test/resources/20/expanded/invalid/ncx-pagetarget-type/EPUB/lorem.xhtml
- src/test/resources/20/expanded/invalid/ncx-pagetarget-type/META-INF/container.xml
- src/test/resources/20/expanded/invalid/ncx-pagetarget-type/mimetype
> [fix #761] Update ncx.rng schema to add fixed list of pageTarget type values

- src/main/resources/com/adobe/epubcheck/schema/20/dtd/svg11.dtd
- src/main/resources/com/adobe/epubcheck/schema/20/rng/svg/svg-style.rng
- src/main/resources/com/adobe/epubcheck/schema/30/mod/svg11/svg11-flat.rnc
- src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java
- src/test/resources/30/single/svg/valid/issue688.svg
> [fix #688] Change style/@type to optional in the SVG Schema/DTD (bugfix)

- src/main/java/com/adobe/epubcheck/ops/OPSHandler30.java
- src/test/resources/30/single/xhtml/valid/svg-links.xhtml
I hope this patch fixes the bug https://github.com/IDPF/epubcheck/issues/680#issuecomment-195761262
> [fix #680] fix incorrect warning ACC_011

- src/test/java/com/adobe/epubcheck/cli/CLITest.java
- src/test/java/com/adobe/epubcheck/nav/NavCheckerTest.java
- src/test/java/com/adobe/epubcheck/ocf/OCFMockPackage.java
- src/test/java/com/adobe/epubcheck/opf/OPFCheckerTest.java
- src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java
- src/test/java/com/adobe/epubcheck/overlay/OverlayCheckerTest.java
- src/test/java/com/adobe/epubcheck/test/api_Test.java
- src/test/java/com/adobe/epubcheck/test/common.java
- src/test/java/com/adobe/epubcheck/test/package_Test.java
Fixes #719.
See #719 for technical details.
> [fix #719] make "mvn test" run on windows

- src/main/java/com/adobe/epubcheck/tool/EpubChecker.java
> [fix #740] Query report message counter to fix wrong exit message for single file validation

- src/main/resources/com/adobe/epubcheck/schema/20/sch/opf.sch
- src/main/resources/com/adobe/epubcheck/schema/30/epub-nav-30.sch
- src/main/resources/com/adobe/epubcheck/schema/30/package-30.sch
- src/test/java/com/adobe/epubcheck/nav/NavCheckerTest.java
- src/test/java/com/adobe/epubcheck/opf/OPFCheckerTest.java
- src/test/resources/20/single/opf/invalid/guide-duplicates.opf
- src/test/resources/30/single/nav/invalid/nav-landmarks-duplicates.xhtml
- src/test/resources/30/single/opf/invalid/guide-duplicates.opf
Fixes #493.
If one of the english native speakers here has better ideas for the message, please tell me.
> [fix #493] Issue a warning for identical guide reference and landmarks items

- README.md
If no one reviews in 2 days, I will merge
> [fix #796] updated info about new email list

- README.md
- src/main/assembly/README-dist.txt
As discussed in todays EpubCheck TaskForce meeting.
> Update list of contributors in README.md and add a maintenance alert

- .travis.yml
- pom.xml
- src/test/java/com/adobe/epubcheck/test/jsonCompare.java
- src/test/resources/com/adobe/epubcheck/test/xhtml/html5_epub3/OPS/xml_version.xhtml
- src/test/resources/com/adobe/epubcheck/test/xhtml/html5_epub3_expected_results.json
Java 9 is about to be released in July 2017.
We should make sure that Java 9 is supported by EpubCheck.
> [WIP] Travis CI: Add JDK9 tests

- .travis.yml
not sure yet which version is supported by Travis ATM
> Travis CI: Add JDK 10 tests

- src/main/java/com/adobe/epubcheck/ctc/EpubNCXCheck.java
- src/test/resources/com/adobe/epubcheck/test/package/path_resolution/OPS/toc.ncx
- src/test/resources/com/adobe/epubcheck/test/package/path_resolution_expected_results.json
When I went through the test in order to fix #813 I couldn't fix one test case where the path of the package was different from the NCX file.
I realized that this was a bug and I separated this cleanup into this pull request fixing the bug.
> Path resolution fix

- README.md
> docs: update link of latest version in README.md

- src/test/java/com/adobe/epubcheck/nav/NavCheckerTest.java
- src/test/resources/30/single/nav/invalid/nav-empty-list.xhtml
> test: add a test for empty lists in nav doc

- src/main/java/com/adobe/epubcheck/util/XmlReportAbstract.java
- src/main/java/com/adobe/epubcheck/vocab/PrefixDeclarationParser.java
try to remove https://travis-ci.org/w3c/epubcheck/jobs/469921868#L2427 and https://travis-ci.org/w3c/epubcheck/jobs/469921868#L2429 .
> Suppress warnings from compiler

- src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/common.rnc
- src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/core-scripting.rnc
- src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/embed.rnc
- src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/epubcheck.patch
- src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/media.rnc
- src/test/java/com/adobe/epubcheck/ops/OPSCheckerTest.java
- src/test/resources/30/single/xhtml/invalid/id-ref-not-found.xhtml
- src/test/resources/30/single/xhtml/valid/id-ref-not-ncname.xhtml
Fix #783
Also update HTML schemas to latest changes from upstream.
> Do not restrict ID refs to NCName

- src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java
- src/test/resources/30/expanded/invalid/remote-script/META-INF/container.xml
- src/test/resources/30/expanded/invalid/remote-script/OPS/content_001.xhtml
- src/test/resources/30/expanded/invalid/remote-script/OPS/nav.xhtml
- src/test/resources/30/expanded/invalid/remote-script/OPS/package.opf
- src/test/resources/30/expanded/invalid/remote-script/mimetype
> Add a test for remote scripts

- src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java
- src/test/resources/30/expanded/valid/foreign-in-link/META-INF/container.xml
- src/test/resources/30/expanded/valid/foreign-in-link/OPS/content_001.xhtml
- src/test/resources/30/expanded/valid/foreign-in-link/OPS/nav.xhtml
- src/test/resources/30/expanded/valid/foreign-in-link/OPS/package.opf
- src/test/resources/30/expanded/valid/foreign-in-link/mimetype
- src/test/resources/30/expanded/valid/foreign-unused/META-INF/container.xml
- src/test/resources/30/expanded/valid/foreign-unused/OPS/content_001.xhtml
- src/test/resources/30/expanded/valid/foreign-unused/OPS/nav.xhtml
- src/test/resources/30/expanded/valid/foreign-unused/OPS/package.opf
- src/test/resources/30/expanded/valid/foreign-unused/mimetype
These were already ignored; this PR just adds some tests.
Close #868
> test: foreign resources unrendered don't need fallbacks

- src/main/java/com/adobe/epubcheck/tool/EpubChecker.java
- src/main/resources/com/adobe/epubcheck/util/messages.properties
- src/test/resources/com/adobe/epubcheck/test/command_line/severity_error_expected_results.txt
- src/test/resources/com/adobe/epubcheck/test/command_line/severity_fatal_expected_results.txt
- src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideBadId_expected_results.txt
- src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideBadMessage_expected_results.txt
- src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideBadSeverity_expected_results.txt
- src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideMissingFile_expected_results.txt
- src/test/resources/com/adobe/epubcheck/test/command_line/severity_overrideOk_expected_results.txt
- src/test/resources/com/adobe/epubcheck/test/command_line/severity_usage_expected_results.txt
- src/test/resources/com/adobe/epubcheck/test/command_line/severity_warning_expected_results.txt
> fix: localize singular/plurals variants in summary

- src/main/java/com/adobe/epubcheck/ocf/OCFChecker.java
- src/main/java/com/adobe/epubcheck/xml/XMLValidators.java
- src/main/resources/com/adobe/epubcheck/schema/30/ocf-encryption-30.sch
- src/test/java/com/adobe/epubcheck/api/Epub30CheckExpandedTest.java
- src/test/resources/30/expanded/invalid/encryption-duplicate-ids/EPUB/content_001.xhtml
- src/test/resources/30/expanded/invalid/encryption-duplicate-ids/EPUB/nav.xhtml
- src/test/resources/30/expanded/invalid/encryption-duplicate-ids/EPUB/package.opf
- src/test/resources/30/expanded/invalid/encryption-duplicate-ids/META-INF/container.xml
- src/test/resources/30/expanded/invalid/encryption-duplicate-ids/META-INF/encryption.xml
- src/test/resources/30/expanded/invalid/encryption-duplicate-ids/mimetype
> feat: check duplicate IDs in the OCF encryption file

- src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/structural.rnc
> add doc-glossary to allowed roles on section

- src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/applications.rnc
- src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/core-scripting.rnc
- src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/embed.rnc
- src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/meta.rnc
- src/main/resources/com/adobe/epubcheck/schema/30/mod/html5/web-forms2.rnc
- src/main/resources/com/adobe/epubcheck/schema/30/mod/svg11/svg-basic-filter.rnc
- src/test/resources/epub3/content-document-xhtml.feature
- src/test/resources/epub3/files/content-document-xhtml/img-alt-missing-error.xhtml
- src/test/resources/epub3/files/content-document-xhtml/img-alt-missing-in-figure-valid.xhtml
- src/test/resources/epub3/files/content-document-xhtml/img-alt-missing-with-title-valid.xhtml
Import changes up to commit validator/validator@224d49b
> Update schemas from the HTML Checker upstream

- src/main/resources/com/adobe/epubcheck/schema/30/package-30.rnc
- src/test/resources/epub3/files/package-document/attr-dir-auto-valid.opf
- src/test/resources/epub3/package-document.feature
> feat: allow 'auto' value for the 'dir' attribute of Package Documents

- src/main/java/com/adobe/epubcheck/xml/handlers/XMLHandler.java
(I think this fixes the location part of #1407)
> fix: regression that lost line and column numbers in messages

- src/main/java/com/adobe/epubcheck/opf/OPFChecker30.java
- src/test/resources/epub3/09-media-overlays/files/mediaoverlays-duration-total-within-tolerance-valid.opf
- src/test/resources/epub3/09-media-overlays/media-overlays.feature
> feat: allow 1s tolerance for media overlays duration sum check

- src/test/resources/epub3/03-resources/files/resources-foreign-script-datablock-valid/EPUB/content_001.xhtml
- src/test/resources/epub3/03-resources/files/resources-foreign-script-datablock-valid/EPUB/nav.xhtml
- src/test/resources/epub3/03-resources/files/resources-foreign-script-datablock-valid/EPUB/package.opf
- src/test/resources/epub3/03-resources/files/resources-foreign-script-datablock-valid/META-INF/container.xml
- src/test/resources/epub3/03-resources/files/resources-foreign-script-datablock-valid/mimetype
- src/test/resources/epub3/03-resources/resources.feature
> test: verify that script data blocks do not require fallbacks

- src/test/java/org/w3c/epubcheck/test/AssertionSteps.java
- src/test/java/org/w3c/epubcheck/test/MessageInfo.java
- src/test/java/org/w3c/epubcheck/test/TestReport.java
- src/test/resources/epub3/06-content-document/content-document-xhtml.feature
> test: test that schematron messages have location info

- src/main/java/com/adobe/epubcheck/overlay/ClipTime.java
> refactor: remove primitive wrapper constructor

- pom.xml
> chore(deps): bump ICU4J from v72.1 to v76.1
